### ISSUE TITLE
KeyError: 'train'

### ISSUE THREAD

**Issue by JingpengSun** [trigeorgis/ComParE2017#2]
I got KeyError when running data_generator.py
Do you have any idea about this error?

E:\Anaconda3\Scripts\ComParE2017>python data_generator.py --wave_folder=path/to/wave_folder --arff_path=ComParE2017_Cold\* --tf_folder=tf_records
Extracting labels from ComParE2017_Cold\*
Creating tfrecords for [train].
Traceback (most recent call last):

  File "<ipython-input-1-3e7ac6d7cf9b>", line 1, in <module>
    runfile('E:/Anaconda3/Scripts/ComParE2017/data_generator.py', wdir='E:/Anaconda3/Scripts/ComParE2017')

  File "E:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "E:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Anaconda3/Scripts/ComParE2017/data_generator.py", line 148, in <module>
    main(FLAGS.wave_folder, FLAGS.arff_path, FLAGS.tf_folder)

  File "E:/Anaconda3/Scripts/ComParE2017/data_generator.py", line 144, in main
    serialize_sample(writer, labels[portion], root_dir, upsample='train' in portion)

KeyError: 'train'

**Comment by hcao720** [comment]
Hello, did you solve it?
